<?php
/**
 * Magecom
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magecom.net so we can send you a copy immediately.
 *
 * @category Magecom
 * @package Magecom_Label
 * @copyright Copyright (c) 2017 Magecom, Inc. (http://www.magecom.net)
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var \Magecom\ProductLabel\Block\Product\View $block */
?>
<?php if ($block->getAttributeValue('label_new')): ?>
    <span class="new-product">
    </span>
<?php endif; ?>

<?php if ($block->getAttributeValue('label_sale')): ?>
    <span class="sale-product">
    </span>
<?php endif; ?>

<?php if ($block->getAttributeValue('label_bestsell')): ?>
    <span class="bestsell-product">
    </span>
<?php endif; ?>

